# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: release

on:
  push:
    branches: [ "master" ]

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up zulu-jdk 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: github-tag-release

  # You may pin to the exact commit or the version.

  # uses: janryWang/github-tag-release@7dbe52cf0967783d198faac8e4b85dc8609572f9

      uses: janryWang/github-tag-release@v0.0.3

      with:

    # the GITHUB_TOKEN

       github_token: ${{ secrets.GITHUB_TOKEN }}

    # Changelog Max Items

       changelog_limit: 50

    # Release Note Title

       release_title: auto release
 
    # Auto Commit Message

       auto_commit_message: auto commit
